### NumPy

NumPy is a fundamental library for scientific computing in python. It provides support of array and matrices, along with collection of mathematic functions to operate on these data structures.

In [1]:
import numpy as np

# create array using numpy 
arr = np.array([1, 2, 3])

In [6]:
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [7]:
arr_copy = arr
print(arr_copy)

[1 2 3]


In [ ]:
arr_copy.reshape(1, 3) # reshape to [1 row, 5 columns]

array([[1, 2, 3]])

In [10]:
print(arr_copy)

[1 2 3]


In [19]:
print(arr_copy.ndim)
print(arr_copy.size)
print(arr_copy.dtype)
print(arr_copy.itemsize) # item size in bytes

1
3
int64
8


Creating arrays with in-built functions:

In [12]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Create a identity matrix:

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

NumPy Vectorized Operations

In [ ]:
vector_arr = np.array([1, 2, 3])
vector_arr2 = np.array([10, 20, 30])

In [23]:
# Element wise addition

print("Addition: ", vector_arr + vector_arr2)

Addition:  [11 22 33]


In [28]:
# Element wise subtraction

print("Subtraction: ", vector_arr2 - vector_arr)

Subtraction:  [ 9 18 27]


NumPy universal functions

In [30]:
arr3 = np.array([25, 36, 512])
print(np.sqrt(arr3))

[ 5.        6.       22.627417]


In [32]:
print(np.exp(arr3))

[7.20048993e+010 4.31123155e+015 2.28441359e+222]


In [33]:
print(np.sin(arr3))

[-0.13235175 -0.99177885  0.07951849]


In [34]:
print(np.log(arr3))

[3.21887582 3.58351894 6.23832463]


Array Slicing and Indexing

In [36]:
arr4 = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])
print(arr4)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [ ]:
arr4[0][0]

np.int64(1)

In [38]:
print(arr4[0][0])

1


In [39]:
print(arr4[1:, 2:])

[[ 6  7]
 [ 9 10]]


In [48]:
print(arr4[0:2, 1:])

[[2 3 4]
 [5 6 7]]


Modify array elements

In [49]:
arr4[0][0] = 100
print(arr4)

[[100   2   3   4]
 [  4   5   6   7]
 [  7   8   9  10]]


In [51]:
arr4[1:] = 100
print(arr4)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


Statistical Concepts
1. Normalization

In [53]:
# mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5, 6])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev

In [54]:
print(normalized_data)

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [55]:
variance = np.var(data)
print(variance)

2.9166666666666665
